env:
  file: <class 'envs.cartpole.cartpole'>
logger:
  dir_name: Cartpole
eps: 10
gamma: .99
T: 200
mono:
  lr: 1.0e-2
reinforce:
  lr: 1.0e-2
avg_reinforce:
  lr: 1.0e-2
batch_size: 8
n_grad_updates: 1
n_traj: 1000
delta: .1
seeds:
- 1
- 2
- 3
- 4
- 5
- 6
- 7
- 8
- 9
- 10