env:
  file: <class 'envs.flatworld.flatworld'>
logger:
  dir_name: FlatWorld
ltl:
  autobuild: False
  formula: "G F (y & X F r) & G!b"
  oa_type: ldba
  rabinizer: ./rabinizer4/bin/ltl2ldba
q_learning:
  batches_per_update: 5
  batch_size: 128
  update_freq__n_episodes: 1
  init_temp: .5
  temp_decay_freq__n_episodes: 100
  temp_decay_rate: .9
  temp_decay_type: 'exponential'
  min_action_temp: .15
  lr: .001
  iterations_per_target_update: 15
testing:
  testing_freq__n_episodes: 1
  num_rollouts: 1
gamma: .95
n_grad_updates: 1
n_traj: 10000
delta: .1
n_seeds: 3
init_seed: 314
T: 100
replay_buffer_size: 5000