env:
  _target_: 'envs.minecraft.Minecraft'
  shape: [10, 10]
  initial_state: [9, 2]
  slip_probability: 0.
classes:
  discrete: <class 'envs.minecraft.minecraft'>
logger:
  dir_name: minecraft
ltl:
  autobuild: False
  formula: GF(gold & XF(work_bench)) & (G !obstacle)
  oa_type: ldba
  rabinizer: ./rabinizer4/bin/ltl2ldba
q_learning:
  batches_per_update: 20
  batch_size: 128
  update_freq__n_episodes: 1
  temp_decay_freq__n_episodes: 25
  temp_decay_rate: .05
  min_action_temp: 0.
  n_traj: 250
  T: 100
  init_temp: .3
  lr: .001
  iterations_per_target_update: 5
  temp_decay_type: 'exponential'
testing:
  testing_freq__n_episodes: 10
  num_rollouts: 1
gamma: .99
n_grad_updates: 1
delta: .1
n_seeds: 10
init_seed: 623
lambda: 60.0
replay_buffer_size: 50000
checkpoint_freq__n_episodes: 50
visualize: True
reward_type: 2